exports.up = function(knex, Promise) {
  return Promise.all([
    knex.schema.createTableIfNotExists('events', function(table){
      table.increments('id').primary()
      table.text('event_name')
      table.text('event_description')
      table.text('start_timezone')
      table.text('start_local_time')
      table.text('start_utc')
      table.text('end_timezone')
      table.text('end_local_time')
      table.text('end_utc')
      table.text('event_created_time')
      table.text('event_changed_at')
      table.text('capacity')
      table.text('status')
      table.text('currency')
      table.text('listed')
      table.text('shareable')
      table.text('online_event')
      table.text('tx_time_limit')
      table.text('hide_start_date')
      table.text('hide_end_date')
      table.text('locale')
      table.text('is_locked')
      table.text('privacy_setting')
      table.text('is_series')
      table.text('is_series_parent')
      table.text('is_reserved_seating')
      table.text('logo_id')
      table.text('organizer_id')
      table.text('venue_id')
      table.text('category_id')
      table.text('subcategory_id')
      table.text('format_id')
      table.text('resource_url')
      table.text('logo_url')
    })
  ])
}
exports.down = function(knex, Promise) {
  knex.schema.dropTable('github_users')
}
